/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
public class aksesoris extends javax.swing.JFrame {

    /**
     * Creates new form aksesoris
     */
    DefaultTableModel model;
    public aksesoris() {
        initComponents();
        String [] judul={"kode aksesoris","nama aksesoris","jenis aksesoris","harga aksesoris"};
        model  = new DefaultTableModel(judul,0);
        jTable_aksesoris.setModel(model);
        tampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_aksesoris = new javax.swing.JTable();
        jBtambah = new javax.swing.JButton();
        jBedit = new javax.swing.JButton();
        jBhapus = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jnm_akse = new javax.swing.JTextField();
        jharga_akse = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jenisaksesoris = new javax.swing.JComboBox<>();
        laporan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jkd_akse = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_aksesoris.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable_aksesoris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_aksesoris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_aksesorisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_aksesoris);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 650, 110));

        jBtambah.setBackground(new java.awt.Color(255, 245, 252));
        jBtambah.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        jBtambah.setText("TAMBAH");
        jBtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtambahActionPerformed(evt);
            }
        });
        jPanel1.add(jBtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 140, 50));

        jBedit.setBackground(new java.awt.Color(255, 245, 252));
        jBedit.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        jBedit.setText("EDIT");
        jBedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditActionPerformed(evt);
            }
        });
        jPanel1.add(jBedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 140, 50));

        jBhapus.setBackground(new java.awt.Color(255, 245, 252));
        jBhapus.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        jBhapus.setText("HAPUS");
        jBhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhapusActionPerformed(evt);
            }
        });
        jPanel1.add(jBhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 130, 50));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 60, 50));

        jnm_akse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jnm_akse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 160, 40));

        jharga_akse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jharga_akse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 160, 40));

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        jLabel1.setText("Kode Aksesoris");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        jLabel2.setText("Nama Aksesoris");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        jLabel3.setText("Jenis Aksesoris");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        jLabel4.setText("Harga Aksesoris");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 30)); // NOI18N
        jLabel5.setText("AKSESORIS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jenisaksesoris.setBackground(new java.awt.Color(255, 245, 252));
        jenisaksesoris.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jenisaksesoris.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "TRIPOD", "FILTER", "REFLECTOR" }));
        jPanel1.add(jenisaksesoris, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 100, 40));

        laporan.setBackground(new java.awt.Color(255, 245, 252));
        laporan.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        laporan.setText("LAPORAN");
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        jPanel1.add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 130, 50));

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 30)); // NOI18N
        jLabel6.setText("SUKA KAMERA SOLO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SK'S.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setText("180101161/Panji Taruna");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jkd_akse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jkd_akse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 160, 40));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 390);

        setSize(new java.awt.Dimension(686, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new menuadmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtambahActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
            cn.createStatement().executeUpdate("insert into aksesoris values"+"('"+jkd_akse.getText()+"','"+jnm_akse.getText()+"','"+jenisaksesoris.getSelectedItem()+"','"+jharga_akse.getText()+"')");
            autonumber();
            tampilkan_data();
            reset();
        } catch (SQLException ex) {
           // Logger.getLogger(aksesoris.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jBtambahActionPerformed

    private void jBeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
            cn.createStatement().executeUpdate("update aksesoris set nama_aksesoris='"+jnm_akse.getText()+"', jenis_aksesoris='"+jenisaksesoris.getSelectedItem()+"', harga_aksesoris='"+jharga_akse.getText()+"' where kd_aksesoris='"+jkd_akse.getText()+"'");
            autonumber();
            tampilkan_data();    
           reset();
        } catch (SQLException ex) {
            //Logger.getLogger(lensa.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null,ex); 
        }

    }//GEN-LAST:event_jBeditActionPerformed

    private void jTable_aksesorisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_aksesorisMouseClicked
        // TODO add your handling code here:
        int i=jTable_aksesoris.getSelectedRow();
        
        if(i>-1){
            jkd_akse.setText(model.getValueAt(i,0).toString());
            jnm_akse.setText(model.getValueAt(i,1).toString());
            jenisaksesoris.setSelectedItem(model.getValueAt(i,2).toString());
            jharga_akse.setText(model.getValueAt(i,3).toString());
        }

    }//GEN-LAST:event_jTable_aksesorisMouseClicked

    private void jBhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhapusActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
            cn.createStatement().executeUpdate("delete from aksesoris where kd_aksesoris='"+jkd_akse.getText()+"'");
            autonumber();
            tampilkan_data();
            reset();
        } catch (SQLException ex) {
            //Logger.getLogger(kamera.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex); 
        }

    }//GEN-LAST:event_jBhapusActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        // TODO add your handling code here:
                                  try {
            HashMap parameter = new HashMap();
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sewa_kamera", "root", "");
            File file = new File("src/laporan/aksesoris.jasper");            
            JasperReport jr =(JasperReport) JRLoader.loadObject(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter,cn);  
           JasperViewer.viewReport(jp,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);         
        } catch (Exception e) {
            e.printStackTrace();
        }
 

    }//GEN-LAST:event_laporanActionPerformed
    private void IDOtomatis  (){
    String sql="select max(right([id_aksesoris],3))as [id_aksesoris] from [aksesoris]";
    
    }

    
    private void reset  (){
        autonumber();
        //jkd_akse.setText("");
        jnm_akse.setText("");
        jenisaksesoris.setSelectedItem("PILIH");
        jharga_akse.setText(""); 
    }                                    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aksesoris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aksesoris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aksesoris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aksesoris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new aksesoris().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBedit;
    private javax.swing.JButton jBhapus;
    private javax.swing.JButton jBtambah;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_aksesoris;
    private javax.swing.JComboBox<String> jenisaksesoris;
    private javax.swing.JTextField jharga_akse;
    private javax.swing.JTextField jkd_akse;
    private javax.swing.JTextField jnm_akse;
    private javax.swing.JButton laporan;
    // End of variables declaration//GEN-END:variables

   private void autonumber(){
    String kd_akse= "AK000";
    int i = 0;
    try{
    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
    Statement st =cn.createStatement();
    String sql= "select kd_aksesoris from aksesoris order by kd_aksesoris desc limit 1 ";
    ResultSet rs = st.executeQuery(sql);
    while(rs.next()){
	kd_akse = rs.getString("kd_aksesoris");
    }
    kd_akse = kd_akse.substring(4);
    i = Integer.parseInt(kd_akse)+1;
    kd_akse= "00"+ i;
    kd_akse= "AK"+ kd_akse.substring(kd_akse.length()-3);
    jkd_akse.setText(kd_akse);
    } catch (SQLException e) {
	//System.out.println(e.getMessage());
        JOptionPane.showMessageDialog(null,e); 
    }
}
 
    
    private void tampilkan_data() {
     model= new DefaultTableModel();
       jTable_aksesoris.setModel(model);
       model.addColumn("kd_aksesoris");
       model.addColumn("nama_aksesoris");
       model.addColumn("jenis_aksesoris");
       model.addColumn("harga_aksesoris");
       
       try{
       Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
      ResultSet res=cn.createStatement().executeQuery("select * FROM aksesoris");
      while(res.next()){
          Object[]obj= new Object[4];
          obj[0]=res.getString("kd_aksesoris");
          obj[1]=res.getString("nama_aksesoris");
          obj[2]=res.getString("jenis_aksesoris");
          obj[3]=res.getString("harga_aksesoris");
          
          model.addRow(obj);
      }
   }
       catch(SQLException err){
           JOptionPane.showMessageDialog(null, err.getMessage());
       }
    }
}
