/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
public class kamera extends javax.swing.JFrame {

    /**
     * Creates new form kamera
     */
    DefaultTableModel model;
    public kamera() throws SQLException {
        initComponents();
        String[] judul={"kode kamera","nama kamera","jenis kamera","harga sewa"};
        model =new DefaultTableModel(judul,0);
        jTable_kamera.setModel(model);
        autonumber();
        tampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTkode_kamera = new javax.swing.JTextField();
        jTnama_kamera = new javax.swing.JTextField();
        jTharga_kamera = new javax.swing.JTextField();
        jB_tambah = new javax.swing.JButton();
        jBedit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_kamera = new javax.swing.JTable();
        jeniskamera = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 30)); // NOI18N
        jLabel1.setText("KAMERA  SUKA SOLO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 30)); // NOI18N
        jLabel2.setText("KAMERA ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        jLabel3.setText("KODE KAMERA    :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        jLabel4.setText("NAMA KAMERA   :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        jLabel5.setText("JENIS KAMERA    :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        jLabel6.setText("HARGA KAMERA :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jTkode_kamera.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTkode_kamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTkode_kameraActionPerformed(evt);
            }
        });
        jPanel1.add(jTkode_kamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 190, 40));

        jTnama_kamera.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTnama_kamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnama_kameraActionPerformed(evt);
            }
        });
        jPanel1.add(jTnama_kamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 190, 40));

        jTharga_kamera.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTharga_kamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTharga_kameraActionPerformed(evt);
            }
        });
        jPanel1.add(jTharga_kamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 190, 40));

        jB_tambah.setBackground(new java.awt.Color(255, 245, 252));
        jB_tambah.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jB_tambah.setText("TAMBAH");
        jB_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_tambahActionPerformed(evt);
            }
        });
        jPanel1.add(jB_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 130, 50));

        jBedit.setBackground(new java.awt.Color(255, 245, 252));
        jBedit.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jBedit.setText("EDIT");
        jBedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditActionPerformed(evt);
            }
        });
        jPanel1.add(jBedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 130, 50));

        jButton3.setBackground(new java.awt.Color(255, 245, 252));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 140, 50));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 70, 50));

        jTable_kamera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_kamera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_kameraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_kamera);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 680, 130));

        jeniskamera.setBackground(new java.awt.Color(255, 245, 252));
        jeniskamera.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jeniskamera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "DSLR", "ACTION CAM", "MIRRORLESS" }));
        jPanel1.add(jeniskamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 110, 40));

        jButton1.setBackground(new java.awt.Color(255, 245, 252));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setText("LAPORAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 140, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SK'S.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setText("180101161/Panji Taruna");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 20));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 420);

        setSize(new java.awt.Dimension(718, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTnama_kameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnama_kameraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnama_kameraActionPerformed

    private void jTharga_kameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTharga_kameraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTharga_kameraActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new menuadmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jB_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_tambahActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
            cn.createStatement().executeUpdate("insert into kamera values"+"('"+jTkode_kamera.getText()+"','"+jTnama_kamera.getText()+"','"+jeniskamera.getSelectedItem()+"','"+jTharga_kamera.getText()+"')");
            autonumber();
            tampilkan();
            reset();
        } catch (SQLException ex) {
            //Logger.getLogger(kamera.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "cek kembali data !!");
        }
    }//GEN-LAST:event_jB_tambahActionPerformed

    private void jBeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
            cn.createStatement().executeUpdate("update kamera set nama_kamera='"+jTnama_kamera.getText()+"', jenis_kamera='"+jeniskamera.getSelectedItem()+"', harga_kamera='"+jTharga_kamera.getText()+"' where kd_kamera='"+jTkode_kamera.getText()+"'");
            autonumber();
            tampilkan();   
            reset();
        } catch (SQLException ex) {
               //Logger.getLogger(kamera.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null,ex); 
        }
    }//GEN-LAST:event_jBeditActionPerformed

    private void jTable_kameraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_kameraMouseClicked
        // TODO add your handling code here:
        int i=jTable_kamera.getSelectedRow();
        
        if(i>-1){
            jTkode_kamera.setText(model.getValueAt(i,0).toString());
            jTnama_kamera.setText(model.getValueAt(i,1).toString());
            jeniskamera.setSelectedItem(model.getValueAt(i,2).toString());
            jTharga_kamera.setText(model.getValueAt(i,3).toString());
        }
    }//GEN-LAST:event_jTable_kameraMouseClicked
    public void tampilkan_data(){
       model= new DefaultTableModel();
       jTable_kamera.setModel(model);
       model.addColumn("kode_kamera");
       model.addColumn("nama_kamera");
       model.addColumn("jenis_kamera");
       model.addColumn("harga_kamera");
       
       try{
       Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
      ResultSet res=cn.createStatement().executeQuery("select * FROM kamera");
      while(res.next()){
          Object[]obj= new Object[4];
          obj[0]=res.getString("kd_kamera");
          obj[1]=res.getString("nama_kamera");
          obj[2]=res.getString("jenis_kamera");
          obj[3]=res.getString("harga_kamera");
          
          model.addRow(obj);
      }
   }
       catch(SQLException err){
           JOptionPane.showMessageDialog(null, err.getMessage());
       }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
            cn.createStatement().executeUpdate("delete from kamera where kd_kamera='"+jTkode_kamera.getText()+"'");
            autonumber();
            tampilkan();
            reset();
        } catch (SQLException ex) {
            //Logger.getLogger(kamera.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex); 
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTkode_kameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTkode_kameraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTkode_kameraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            HashMap parameter = new HashMap();
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sewa_kamera", "root", "");
            File file = new File("src/laporan/kamera.jasper");            
            JasperReport jr =(JasperReport) JRLoader.loadObject(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter,cn);  
           JasperViewer.viewReport(jp,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);       
               
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void reset  (){
        autonumber();
        //jTkode_kamera.setText("");
        jTnama_kamera.setText("");
        jeniskamera.setSelectedItem("PILIH");
        jTharga_kamera.setText(""); 
    }                              
    
    private void autonumber(){
    String kd_kamera= "KM0000";
    int i = 0;
    try{
    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
    Statement st =cn.createStatement();
    String sql= "select kd_kamera from kamera";
    ResultSet rs = st.executeQuery(sql);
    while(rs.next()){
	kd_kamera = rs.getString("kd_kamera");
    }
    kd_kamera  = kd_kamera.substring(4);
    i = Integer.parseInt(kd_kamera)+1;
    kd_kamera = "00"+i;
    kd_kamera = "KM"+ kd_kamera.substring(kd_kamera.length()-3);
    jTkode_kamera.setText(kd_kamera);
    } catch (SQLException e) {
	System.out.println(e.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kamera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new kamera().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(kamera.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_tambah;
    private javax.swing.JButton jBedit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_kamera;
    private javax.swing.JTextField jTharga_kamera;
    private javax.swing.JTextField jTkode_kamera;
    private javax.swing.JTextField jTnama_kamera;
    private javax.swing.JComboBox<String> jeniskamera;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() throws SQLException {
      //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    int row = jTable_kamera.getRowCount();
    for(int a= 0; a<row;a++){
        model.removeRow(0);
    }
      try{
      Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
      ResultSet rs=cn.createStatement().executeQuery("select * FROM kamera");
      while(rs.next()){
          String data[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
          model.addRow(data);
      }
    } catch (SQLException ex){
        Logger.getLogger(kamera.class.getName()).log(Level.SEVERE, null, ex);
    }
     

    }
}
