
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class menuadmin extends javax.swing.JFrame {

    /**
     * Creates new form halamanutama
     */
    public menuadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBkamera = new javax.swing.JButton();
        jBlensa = new javax.swing.JButton();
        jBkeluar = new javax.swing.JButton();
        jBaksesoris1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(12, 197, 13));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 245, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELAMAT DATANG DI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 260, -1));

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SUKA KAMERA SOLO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 50, 260, -1));

        jBkamera.setBackground(new java.awt.Color(255, 245, 252));
        jBkamera.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jBkamera.setText("SEWA KAMERA");
        jBkamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBkameraActionPerformed(evt);
            }
        });
        jPanel1.add(jBkamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 271, 45));

        jBlensa.setBackground(new java.awt.Color(255, 245, 252));
        jBlensa.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jBlensa.setText("SEWA LENSA");
        jBlensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlensaActionPerformed(evt);
            }
        });
        jPanel1.add(jBlensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 271, 45));

        jBkeluar.setBackground(new java.awt.Color(255, 245, 252));
        jBkeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBkeluar.setText("KELUAR");
        jBkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(jBkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        jBaksesoris1.setBackground(new java.awt.Color(255, 245, 252));
        jBaksesoris1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jBaksesoris1.setText("SEWA AKSESORIS KAMERA");
        jBaksesoris1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaksesoris1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBaksesoris1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 45));

        jButton1.setBackground(new java.awt.Color(255, 245, 252));
        jButton1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jButton1.setText("LAPORAN TRANSAKSI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 270, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SK'S.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setText("180101161/Panji Taruna");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 400);

        setSize(new java.awt.Dimension(456, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBkameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBkameraActionPerformed
        try {
            // TODO add your handling code here:
            new kamera().setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(menuadmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBkameraActionPerformed

    private void jBkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBkeluarActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBkeluarActionPerformed

    private void jBlensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlensaActionPerformed
        try {
            // TODO add your handling code here:
            new lensa().setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(menuadmin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBlensaActionPerformed

    private void jBaksesoris1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaksesoris1ActionPerformed
        // TODO add your handling code here:
        new aksesoris().setVisible(true);
        dispose();

    }//GEN-LAST:event_jBaksesoris1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                                          try {
            HashMap parameter = new HashMap();
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sewa_kamera", "root", "");
            File file = new File("src/laporan/transaksi.jasper");            
            JasperReport jr =(JasperReport) JRLoader.loadObject(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter,cn);  
           JasperViewer.viewReport(jp,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);         
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBaksesoris1;
    private javax.swing.JButton jBkamera;
    private javax.swing.JButton jBkeluar;
    private javax.swing.JButton jBlensa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
