/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
public class transaksi extends javax.swing.JFrame {
    private Statement st;
    private Connection Con;
    private ResultSet Rs;
    private String Sql="";
    private String host;

    /**
     * Creates new form transaksi
     */
        DefaultTableModel model;
    public transaksi() {
        initComponents();
            String[] judul={"no transaksi","id pelanggan","kode kamera","nama kamera","harga kamera","jmlsw kamera","lamasw kamera","kode lensa","nama lensa","harga lensa","jmlsw lensa","lamasw lensa","kode akse","nama aksesoris","harga aksesoris","jmlsw akse","lamasw akse","Total","bayar","kembali"};
        model =new DefaultTableModel(judul,0);
        jTransaksi.setModel(model);
        autonumber();
        tampilkan_data();
        tkd_kamera();
        tkd_lensa();
        tkd_aksesoris();
     
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TAMBAH = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        harga_kamera = new javax.swing.JTextField();
        jmlsw_kamera = new javax.swing.JTextField();
        lamasw_kamera = new javax.swing.JTextField();
        harga_akse = new javax.swing.JTextField();
        jmlsw_akse = new javax.swing.JTextField();
        lamasw_akse = new javax.swing.JTextField();
        harga_lensa = new javax.swing.JTextField();
        jmlsw_lensa = new javax.swing.JTextField();
        total_biaya = new javax.swing.JTextField();
        lamasw_lensa = new javax.swing.JTextField();
        CB_kamera = new javax.swing.JComboBox<>();
        CB_lensa = new javax.swing.JComboBox<>();
        CB_aksesoris = new javax.swing.JComboBox<>();
        jno_transaksi = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTransaksi = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        nama_kamera = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        nama_lensa = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        nama_akse = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        kembali = new javax.swing.JTextField();
        sub_lensa = new javax.swing.JLabel();
        sub_kamera = new javax.swing.JLabel();
        sub_aksesoris = new javax.swing.JLabel();
        laporan = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        id_pelanggan = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        admin = new javax.swing.JMenu();
        EXIT = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 245, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel1.setText("SUKA KAMERA SOLO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, 50));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setText("ID KAMERA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setText("LAMA SEWA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel4.setText("/ HARI");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setText("JUMLAH SEWA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setText("HARGA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setText("ID LENSA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setText("NAMA LENSA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel9.setText("/ HARI");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setText("JUMLAH SEWA");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel11.setText("LAMA SEWA");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel12.setText("ID AKSESORIS");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel13.setText("NAMA AKSESORIS");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, -1, -1));

        jLabel14.setText("/ HARI");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 180, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel15.setText("JUMLAH SEWA");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel16.setText("LAMA SEWA");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, -1, -1));

        TAMBAH.setBackground(new java.awt.Color(255, 245, 252));
        TAMBAH.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        TAMBAH.setText("TAMBAH");
        TAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAMBAHActionPerformed(evt);
            }
        });
        jPanel1.add(TAMBAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 140, 40));

        edit.setBackground(new java.awt.Color(255, 245, 252));
        edit.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 170, 40));

        hapus.setBackground(new java.awt.Color(255, 245, 252));
        hapus.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 140, 40));

        jLabel17.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel17.setText("SELAMAT DATANG DI RENTAL KAMERA");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 710, 50));

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel18.setText("KEMBALI");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 250, -1, -1));

        harga_kamera.setBackground(new java.awt.Color(255, 245, 252));
        harga_kamera.setText("-");
        harga_kamera.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(harga_kamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 160, 30));

        jmlsw_kamera.setText("0");
        jmlsw_kamera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jmlsw_kameraKeyTyped(evt);
            }
        });
        jPanel1.add(jmlsw_kamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 160, -1));

        lamasw_kamera.setText("0");
        lamasw_kamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamasw_kameraActionPerformed(evt);
            }
        });
        lamasw_kamera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lamasw_kameraKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lamasw_kameraKeyReleased(evt);
            }
        });
        jPanel1.add(lamasw_kamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 160, -1));

        harga_akse.setBackground(new java.awt.Color(255, 245, 252));
        harga_akse.setText("-");
        harga_akse.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(harga_akse, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 170, 170, 30));

        jmlsw_akse.setText("0");
        jmlsw_akse.setToolTipText("");
        jmlsw_akse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlsw_akseActionPerformed(evt);
            }
        });
        jmlsw_akse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jmlsw_akseKeyReleased(evt);
            }
        });
        jPanel1.add(jmlsw_akse, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, 170, -1));

        lamasw_akse.setText("0");
        lamasw_akse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamasw_akseActionPerformed(evt);
            }
        });
        lamasw_akse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lamasw_akseKeyReleased(evt);
            }
        });
        jPanel1.add(lamasw_akse, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 170, -1));

        harga_lensa.setBackground(new java.awt.Color(255, 245, 252));
        harga_lensa.setText("-");
        harga_lensa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(harga_lensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 160, 30));

        jmlsw_lensa.setText("0");
        jPanel1.add(jmlsw_lensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 160, -1));
        jPanel1.add(total_biaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 120, 170, 40));

        lamasw_lensa.setText("0");
        lamasw_lensa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lamasw_lensaKeyReleased(evt);
            }
        });
        jPanel1.add(lamasw_lensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 160, -1));

        CB_kamera.setBackground(new java.awt.Color(255, 245, 252));
        CB_kamera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CB_kamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_kameraActionPerformed(evt);
            }
        });
        jPanel1.add(CB_kamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 160, -1));

        CB_lensa.setBackground(new java.awt.Color(255, 245, 252));
        CB_lensa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CB_lensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_lensaActionPerformed(evt);
            }
        });
        jPanel1.add(CB_lensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 160, -1));

        CB_aksesoris.setBackground(new java.awt.Color(255, 245, 252));
        CB_aksesoris.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CB_aksesoris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_aksesorisActionPerformed(evt);
            }
        });
        jPanel1.add(CB_aksesoris, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 170, -1));

        jno_transaksi.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jPanel1.add(jno_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 100, 50));

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel19.setText("No.Transaksi");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, -1, -1));

        jTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTransaksi);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 1260, 110));

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel20.setText("NAMA KAMERA");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        nama_kamera.setBackground(new java.awt.Color(255, 245, 252));
        nama_kamera.setText("-");
        nama_kamera.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(nama_kamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 160, -1));

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel21.setText("HARGA");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        nama_lensa.setBackground(new java.awt.Color(255, 245, 252));
        nama_lensa.setText("-");
        nama_lensa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nama_lensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_lensaActionPerformed(evt);
            }
        });
        jPanel1.add(nama_lensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 160, -1));

        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel22.setText("HARGA");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));

        nama_akse.setBackground(new java.awt.Color(255, 245, 252));
        nama_akse.setText("-");
        nama_akse.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nama_akse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_akseActionPerformed(evt);
            }
        });
        jPanel1.add(nama_akse, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 150, 170, -1));

        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayarKeyReleased(evt);
            }
        });
        jPanel1.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 190, 170, 50));

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel23.setText("TOTAL");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 100, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel24.setText("BAYAR");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 170, -1, -1));
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 270, 170, 40));

        sub_lensa.setForeground(new java.awt.Color(240, 240, 240));
        sub_lensa.setText("0");
        jPanel1.add(sub_lensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        sub_kamera.setForeground(new java.awt.Color(240, 240, 240));
        sub_kamera.setText("0");
        jPanel1.add(sub_kamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        sub_aksesoris.setForeground(new java.awt.Color(240, 240, 240));
        sub_aksesoris.setText("0");
        jPanel1.add(sub_aksesoris, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        laporan.setBackground(new java.awt.Color(255, 245, 252));
        laporan.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        laporan.setText("LAPORAN");
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        jPanel1.add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 120, 40));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SK'S.jpg"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        id_pelanggan.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        id_pelanggan.setToolTipText("");
        jPanel1.add(id_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 160, 30));

        jLabel26.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("ID PELANGGAN");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 160, 30));

        jLabel27.setText("180101161/Panji Taruna");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 470);

        admin.setText("ADMIN");
        admin.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jMenuBar1.add(admin);

        EXIT.setText("KELUAR");
        EXIT.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        EXIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXITMouseClicked(evt);
            }
        });
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jMenuBar1.add(EXIT);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1298, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
                try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
            cn.createStatement().executeUpdate("update transaksi_kamera set id_pelanggan= '"+id_pelanggan.getText()+"',kd_kamera='"+CB_kamera.getSelectedItem()+"',nama_kamera='"+nama_kamera.getText()+"',harga_kamera='"+harga_kamera.getText()+"',jmlsw_kamera='"+jmlsw_kamera.getText()+"',lamasw_kamera='"+lamasw_kamera.getText()+"',kd_lensa='"+CB_lensa.getSelectedItem()+"',nama_lensa='"+nama_lensa.getText()+"',harga_lensa='"+harga_lensa.getText()+"',jmlsw_lensa='"+jmlsw_lensa.getText()+"',lamasw_lensa='"+lamasw_lensa.getText()+"',kd_aksesoris='"+CB_aksesoris.getSelectedItem()+"',nama_aksesoris='"+nama_akse.getText()+"',harga_aksesoris='"+harga_akse.getText()+"',jmlsw_akse='"+jmlsw_akse.getText()+"',lamasw_akse='"+lamasw_akse.getText()+"',total='"+total_biaya.getText()+"',bayar='"+bayar.getText()+"',kembali='"+kembali.getText()+"' where no_transaksi='"+jno_transaksi.getText()+"'");
            
            JOptionPane.showMessageDialog(null,"edit data berhasil");
            autonumber();
            tampilkan_data();   
            reset();
        } catch (SQLException ex) {
               //Logger.getLogger(kamera.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null,ex); 
        }

    }//GEN-LAST:event_editActionPerformed

    private void CB_kameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_kameraActionPerformed
        // TODO add your handling code here:
    thn_kamera();
    nama_kamera.enable(false);
    harga_kamera.enable(false);
    }//GEN-LAST:event_CB_kameraActionPerformed

    private void jmlsw_kameraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmlsw_kameraKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jmlsw_kameraKeyTyped

    private void lamasw_kameraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamasw_kameraKeyTyped
        // TODO add your handling code here:                
    }//GEN-LAST:event_lamasw_kameraKeyTyped

    private void nama_lensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_lensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_lensaActionPerformed

    private void nama_akseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_akseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_akseActionPerformed

    private void lamasw_kameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamasw_kameraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamasw_kameraActionPerformed

    private void lamasw_kameraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamasw_kameraKeyReleased
        // TODO add your handling code here:
        if(lamasw_kamera.getText() != null){
                    int harga,lama,jumlah ;
                    harga= Integer.parseInt(harga_kamera.getText());
                    lama= Integer.parseInt(lamasw_kamera.getText());
                    jumlah= Integer.parseInt(jmlsw_kamera.getText());
                int total= harga * jumlah * lama ;
                
                 sub_kamera.setText(Integer.toString(total));
                 total = Integer.parseInt(sub_lensa.getText()) + Integer.parseInt(sub_kamera.getText())+ Integer.parseInt(sub_aksesoris.getText());
                 total_biaya.setText(Integer.toString(total));
                
        }
    }//GEN-LAST:event_lamasw_kameraKeyReleased

    private void lamasw_lensaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamasw_lensaKeyReleased
        // TODO add your handling code here:
        if(lamasw_lensa.getText() != null){
                    int harga,lama,jumlah ;
                    harga= Integer.parseInt(harga_lensa.getText());
                    lama= Integer.parseInt(lamasw_lensa.getText());
                    jumlah= Integer.parseInt(jmlsw_lensa.getText());
                int total= harga * jumlah * lama ;
                total_biaya.setText(Integer.toString(total));
                
                    sub_lensa.setText(Integer.toString(total));
                    total = Integer.parseInt(sub_lensa.getText()) + Integer.parseInt(sub_kamera.getText())+ Integer.parseInt(sub_aksesoris.getText());
                    total_biaya.setText(Integer.toString(total));                    
                
        }
    }//GEN-LAST:event_lamasw_lensaKeyReleased

    private void lamasw_akseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamasw_akseKeyReleased
        // TODO add your handling code here:
        if(lamasw_akse.getText() != null){
                    int harga,lama,jumlah ;
                    harga= Integer.parseInt(harga_akse.getText());
                    lama= Integer.parseInt(lamasw_akse.getText());
                    jumlah= Integer.parseInt(jmlsw_akse.getText());
                int total= harga * jumlah * lama ;
                total_biaya.setText(Integer.toString(total));
                
                sub_aksesoris.setText(Integer.toString(total));
                    total = Integer.parseInt(sub_lensa.getText()) + Integer.parseInt(sub_kamera.getText())+ Integer.parseInt(sub_aksesoris.getText());
                    total_biaya.setText(Integer.toString(total)); 
                
        }
    }//GEN-LAST:event_lamasw_akseKeyReleased

    private void CB_lensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_lensaActionPerformed
        // TODO add your handling code here:
        thn_lensa();
    nama_lensa.enable(false);
    harga_lensa.enable(false);
    }//GEN-LAST:event_CB_lensaActionPerformed

    private void CB_aksesorisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_aksesorisActionPerformed
        // TODO add your handling code here:
        thn_aksesoris();
    nama_akse.enable(false);
    harga_akse.enable(false);
    }//GEN-LAST:event_CB_aksesorisActionPerformed

    private void TAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAMBAHActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
            cn.createStatement().executeUpdate("insert into transaksi_kamera values"+"('"+jno_transaksi.getText()+"','"+id_pelanggan.getText()+"','"+CB_kamera.getSelectedItem()+"','"+nama_kamera.getText()+"','"+harga_kamera.getText()+"','"+jmlsw_kamera.getText()+"','"+lamasw_kamera.getText()+"','"+CB_lensa.getSelectedItem()+"','"+nama_lensa.getText()+"','"+harga_lensa.getText()+"','"+jmlsw_lensa.getText()+"','"+lamasw_lensa.getText()+"','"+CB_aksesoris.getSelectedItem()+"','"+nama_akse.getText()+"','"+harga_akse.getText()+"','"+jmlsw_akse.getText()+"','"+lamasw_akse.getText()+"','"+total_biaya.getText()+"','"+bayar.getText()+"','"+kembali.getText()+"')");
            autonumber();
            tampilkan_data();
            reset();
        } catch (SQLException ex) {
            //Logger.getLogger(kamera.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_TAMBAHActionPerformed

    private void jTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTransaksiMouseClicked
        // TODO add your handling code here:
                int i=jTransaksi.getSelectedRow();
        
        if(i>-1){
            jno_transaksi.setText(model.getValueAt(i,0).toString());
            id_pelanggan.setText(model.getValueAt(i,1).toString());
            CB_kamera.setSelectedItem(model.getValueAt(i,2).toString());
            nama_kamera.setText(model.getValueAt(i,3).toString());
            harga_kamera.setText(model.getValueAt(i,4).toString());
            jmlsw_kamera.setText(model.getValueAt(i,5).toString());
            lamasw_kamera.setText(model.getValueAt(i,6).toString());
            CB_lensa.setSelectedItem(model.getValueAt(i,7).toString());
            nama_lensa.setText(model.getValueAt(i,8).toString());
            harga_lensa.setText(model.getValueAt(i,9).toString());
            jmlsw_lensa.setText(model.getValueAt(i,10).toString());
            lamasw_lensa.setText(model.getValueAt(i,11).toString());
            CB_aksesoris.setSelectedItem(model.getValueAt(i,12).toString());
            nama_akse.setText(model.getValueAt(i,13).toString());
            harga_akse.setText(model.getValueAt(i,14).toString());
            jmlsw_akse.setText(model.getValueAt(i,15).toString());
            lamasw_akse.setText(model.getValueAt(i,16).toString());
            total_biaya.setText(model.getValueAt(i,17).toString());
            bayar.setText(model.getValueAt(i,18).toString());
            kembali.setText(model.getValueAt(i,19).toString());
        }

        
      
        
    }//GEN-LAST:event_jTransaksiMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
            cn.createStatement().executeUpdate("delete from transaksi_kamera where no_transaksi='"+jno_transaksi.getText()+"'");
            JOptionPane.showMessageDialog(null,"hapus data berhasil");
            autonumber();
            tampilkan_data();   
            reset();
        } catch (SQLException ex) {
               //Logger.getLogger(kamera.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null,ex); 
        } 
    }//GEN-LAST:event_hapusActionPerformed

    private void jmlsw_akseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlsw_akseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlsw_akseActionPerformed

    private void lamasw_akseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamasw_akseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamasw_akseActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyReleased
        // TODO add your handling code here:
                if(total_biaya.getText() != null){
                    int total,pembayaran ;
                    total= Integer.parseInt(total_biaya.getText());
                    pembayaran= Integer.parseInt(bayar.getText());
                int kembalian=  pembayaran - total ;
                kembali.setText(Integer.toString(kembalian)); 
              }

    }//GEN-LAST:event_bayarKeyReleased

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
         new Login().setVisible(true);
         dispose();
    }//GEN-LAST:event_adminActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
         dispose();
    }//GEN-LAST:event_adminMouseClicked

    private void EXITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_EXITMouseClicked

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        // TODO add your handling code here:
               try {
            HashMap parameter = new HashMap();
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sewa_kamera", "root", "");
            File file = new File("src/laporan/transaksi.jasper");            
            JasperReport jr =(JasperReport) JRLoader.loadObject(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter,cn);  
           JasperViewer.viewReport(jp,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);       
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_laporanActionPerformed

    private void jmlsw_akseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmlsw_akseKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlsw_akseKeyReleased
public void thn_kamera(){
        try{
      Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
      ResultSet rs=cn.createStatement().executeQuery("select * FROM kamera where kd_kamera='"+CB_kamera.getSelectedItem()+"'");
      while(rs.next()){
         nama_kamera.setText(rs.getString("nama_kamera"));
         harga_kamera.setText(rs.getString("harga_kamera"));
         
      }
    } catch (SQLException ex){
        Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
    }
}
public void thn_lensa(){
        try{
      Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
      ResultSet rs=cn.createStatement().executeQuery("select * FROM lensa where kd_lensa='"+CB_lensa.getSelectedItem()+"'");
      while(rs.next()){
         nama_lensa.setText(rs.getString("nama_lensa"));
         harga_lensa.setText(rs.getString("harga_lensa"));
         
      }
    } catch (SQLException ex){
        Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
    }
}
public void thn_aksesoris(){
        try{
      Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
      ResultSet rs=cn.createStatement().executeQuery("select * FROM aksesoris where kd_aksesoris='"+CB_aksesoris.getSelectedItem()+"'");
      while(rs.next()){
         nama_akse.setText(rs.getString("nama_aksesoris"));
         harga_akse.setText(rs.getString("harga_aksesoris"));
         
      }
    } catch (SQLException ex){
        Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
    }
}

public void tkd_kamera(){
    CB_kamera.removeAllItems();
        try{
      Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
      ResultSet rs=cn.createStatement().executeQuery("select kd_kamera FROM kamera");
      while(rs.next()){
         CB_kamera.addItem(rs.getString("kd_kamera"));
      }
    } catch (SQLException ex){
        Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
    }
}
public void tkd_lensa(){
    CB_lensa.removeAllItems();
        try{
      Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
      ResultSet rs=cn.createStatement().executeQuery("select kd_lensa FROM lensa");
      while(rs.next()){
         CB_lensa.addItem(rs.getString("kd_lensa"));
      }
    } catch (SQLException ex){
        Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
    }
}
public void tkd_aksesoris(){
    CB_aksesoris.removeAllItems();
        try{
      Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
      ResultSet rs=cn.createStatement().executeQuery("select kd_aksesoris FROM aksesoris");
      while(rs.next()){
         CB_aksesoris.addItem(rs.getString("kd_aksesoris"));
      }
    } catch (SQLException ex){
        Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
    }
}


/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_aksesoris;
    private javax.swing.JComboBox<String> CB_kamera;
    private javax.swing.JComboBox<String> CB_lensa;
    private javax.swing.JMenu EXIT;
    private javax.swing.JButton TAMBAH;
    private javax.swing.JMenu admin;
    private javax.swing.JTextField bayar;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga_akse;
    private javax.swing.JTextField harga_kamera;
    private javax.swing.JTextField harga_lensa;
    private javax.swing.JTextField id_pelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTransaksi;
    private javax.swing.JTextField jmlsw_akse;
    private javax.swing.JTextField jmlsw_kamera;
    private javax.swing.JTextField jmlsw_lensa;
    private javax.swing.JTextField jno_transaksi;
    private javax.swing.JTextField kembali;
    private javax.swing.JTextField lamasw_akse;
    private javax.swing.JTextField lamasw_kamera;
    private javax.swing.JTextField lamasw_lensa;
    private javax.swing.JButton laporan;
    private javax.swing.JTextField nama_akse;
    private javax.swing.JTextField nama_kamera;
    private javax.swing.JTextField nama_lensa;
    private javax.swing.JLabel sub_aksesoris;
    private javax.swing.JLabel sub_kamera;
    private javax.swing.JLabel sub_lensa;
    private javax.swing.JTextField total_biaya;
    // End of variables declaration//GEN-END:variables

    private void tampilkan_data() {
    //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    int row = jTransaksi.getRowCount();
    for(int a= 0; a<row;a++){
        model.removeRow(0);
    }
      try{
      Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
      ResultSet rs=cn.createStatement().executeQuery("SELECT * FROM transaksi_kamera");
      while(rs.next()){
          String data[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13),rs.getString(14),rs.getString(15),rs.getString(16),rs.getString(17),rs.getString(18),rs.getString(19),rs.getString(20)};
          model.addRow(data);
      }
    } catch (SQLException ex){
        Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
    }
 }
 private void autonumber(){
    String no_transaksi= "TS000";
    int i = 0;
    try{
    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sewa_kamera","root","");
    Statement st =cn.createStatement();
    String sql= "select no_transaksi from transaksi_kamera order by no_transaksi desc limit 1 ";
    ResultSet rs = st.executeQuery(sql);
    while(rs.next()){
	no_transaksi = rs.getString("no_transaksi");
    }
    no_transaksi = no_transaksi.substring(4);
    i = Integer.parseInt(no_transaksi)+1;
    no_transaksi= "00"+ i;
    no_transaksi= "TS"+ no_transaksi.substring(no_transaksi.length()-3);
    jno_transaksi.setText(no_transaksi);
    } catch (SQLException e) {
	//System.out.println(e.getMessage());
        JOptionPane.showMessageDialog(null,e); 
    }
 }
  private void reset  (){
            autonumber();
            CB_kamera.setSelectedItem("");
            id_pelanggan.setText("");
            nama_kamera.setText("-");
            harga_kamera.setText("0");
            jmlsw_kamera.setText("0");
            lamasw_kamera.setText("0");
            CB_lensa.setSelectedItem("");
            nama_lensa.setText("-");
            harga_lensa.setText("0");
            jmlsw_lensa.setText("0");
            lamasw_lensa.setText("0");
            CB_aksesoris.setSelectedItem("");
            nama_akse.setText("-");
            harga_akse.setText("0");
            jmlsw_akse.setText("0");
            lamasw_akse.setText("0");
            total_biaya.setText("0");
            bayar.setText("0");
            kembali.setText("0");    
  }     
}